### ISSUE TITLE
Design inconsistencies in the ?

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/ShipporiAntique#4]
There seems to be two different forms of the ? that are used throughout the Latin design set. 
<img width="171" alt="Screen Shot 2020-11-06 at 1 43 03 PM" src="https://user-images.githubusercontent.com/8460297/98417797-72b94780-2036-11eb-9dde-8e3096ad1910.png">

**Comment by fontdasu** [comment]
This font is perfect for manga creators.

The "?" And "!" Used in manga lines use roman type.

This is the style that the Japanese publishing industry has been using for over 60 years.

However, the characters used in Latin are designed in sans serif.

Since "?" Is often used in Japanese, it is designed with priority given to displaying in Roman type.

It is very rare to display Latin in Japanese manga.

![sample3](https://user-images.githubusercontent.com/55616797/98436469-e6cf1a80-211e-11eb-8965-8b37be6d250c.jpg)

I have recorded the sans-serif glyphs of "!" And "?" As alternates.

![sample4](https://user-images.githubusercontent.com/55616797/98436472-ea62a180-211e-11eb-8082-ceeb20185d49.jpg)

**Comment by aaronbell** [comment]
Thanks for the additional context and sample images! 

My concern in this case is primarily that you have two interrelated codepoints (exclam / exclamdown and question / questiondown) which *should* look the same, but look different here. It could lead to a situation where someone writes `¿que?` and gets:

<img width="438" alt="Screen Shot 2020-11-08 at 9 12 50 AM" src="https://user-images.githubusercontent.com/8460297/98471637-9d281380-21a2-11eb-92de-6b1f72aff0a4.png">

Do you see what I mean (also, note that the question down should be flipped)? So while I totally understand that this font is intended for Manga applications, and in such conditions, having different designs is totally appropriate, it feels like an unsuspecting user could find themselves with seemingly inconsistent design. I feel like there could be another mechanism (perhaps OT? You could swap in the manga-style punctuation when following Kana/Kanji) for placing the properly designed punctuation in the proper place.

**Comment by fontdasu** [comment]
I changed the settings in the same way as the specification of the comic font called Antic Cezanne.
https://fontworks.co.jp/fontsearch/AnticCezannePro-M/

Make only .full fonts brush-like typeface.
Please check the latest file.

**Comment by aaronbell** [comment]
Looks good :). Thanks!
